-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 18:03:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema distribuidora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema distribuidora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `distribuidora` DEFAULT CHARACTER SET utf8 ;
USE `distribuidora` ;

-- -----------------------------------------------------
-- Table `distribuidora`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `classificacao_indicativa` VARCHAR(3) NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `produtora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`comprador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`jogos_possuem_generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`jogos_possuem_generos` (
  `jogos_id` INT NOT NULL,
  `generos_id` INT NOT NULL,
  PRIMARY KEY (`jogos_id`, `generos_id`),
  INDEX `fk_jogos_has_generos_generos1_idx` (`generos_id` ASC),
  INDEX `fk_jogos_has_generos_jogos_idx` (`jogos_id` ASC),
  CONSTRAINT `fk_jogos_has_generos_jogos`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `distribuidora`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogos_has_generos_generos1`
    FOREIGN KEY (`generos_id`)
    REFERENCES `distribuidora`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`tipo_pagamento` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distribuidora`.`comprador_compra_jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distribuidora`.`comprador_compra_jogos` (
  `comprador_id` INT NOT NULL,
  `jogos_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_compra` FLOAT(5,2) NOT NULL,
  `tipo_pagamento_id` INT NOT NULL,
  PRIMARY KEY (`comprador_id`, `jogos_id`, `tipo_pagamento_id`),
  INDEX `fk_comprador_has_jogos_jogos1_idx` (`jogos_id` ASC),
  INDEX `fk_comprador_has_jogos_comprador1_idx` (`comprador_id` ASC),
  INDEX `fk_comprador_compra_jogos_tipo_pagamento1_idx` (`tipo_pagamento_id` ASC),
  CONSTRAINT `fk_comprador_has_jogos_comprador1`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `distribuidora`.`comprador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprador_has_jogos_jogos1`
    FOREIGN KEY (`jogos_id`)
    REFERENCES `distribuidora`.`jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprador_compra_jogos_tipo_pagamento1`
    FOREIGN KEY (`tipo_pagamento_id`)
    REFERENCES `distribuidora`.`tipo_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
